#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
from collections import defaultdict, deque
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MEM = ROOT / "docs" / "memory"

NODE_FILES = [
    MEM / "psi-memory-nodes-01.tsv",
    MEM / "psi-memory-nodes-history-01.tsv",
    MEM / "psi-memory-nodes-bridges-01.tsv",
]
EDGE_FILES = [
    MEM / "psi-memory-edges-history-01.tsv",
    MEM / "psi-memory-edges-bridges-01.tsv",
]
NAVIGABLE = {
    "MEMBER_OF",
    "REGRESSION_FOR",
    "HARD_DEPENDS_ON",
    "USES_DEFINITION",
    "USES_LEMMA",
}


def read_nodes() -> dict[str, dict[str, str]]:
    nodes: dict[str, dict[str, str]] = {}
    for path in NODE_FILES:
        with path.open(encoding="utf-8", newline="") as fh:
            for row in csv.DictReader(fh, delimiter="\t"):
                node_id = row["id"].strip()
                assert node_id and node_id not in nodes, f"duplicate/empty node: {node_id}"
                nodes[node_id] = row
    return nodes


def read_edges() -> list[dict[str, str]]:
    edges: list[dict[str, str]] = []
    for path in EDGE_FILES:
        with path.open(encoding="utf-8", newline="") as fh:
            edges.extend(csv.DictReader(fh, delimiter="\t"))
    return edges


def bounded_view(start: str, radius: int, edges: list[dict[str, str]]) -> set[str]:
    by_source: dict[str, list[str]] = defaultdict(list)
    for edge in edges:
        if edge["relation"] in NAVIGABLE:
            by_source[edge["from"]].append(edge["to"])

    seen = {start}
    queue = deque([(start, 0)])
    while queue:
        node, depth = queue.popleft()
        if depth >= radius:
            continue
        for target in by_source.get(node, []):
            if target not in seen:
                seen.add(target)
                queue.append((target, depth + 1))
    return seen


def build_pack(start: str, radius: int) -> tuple[list[str], list[str], list[str]]:
    nodes = read_nodes()
    assert start in nodes, f"unknown start node: {start}"
    view = bounded_view(start, radius, read_edges())

    file_sources: set[str] = set()
    external_sources: set[str] = set()
    for node_id in view:
        source = nodes[node_id]["source"].strip()
        if not source:
            continue
        if (ROOT / source).is_file():
            file_sources.add(source)
        else:
            external_sources.add(source)

    return sorted(view), sorted(file_sources), sorted(external_sources)


def render(start: str, radius: int) -> str:
    view, files, external = build_pack(start, radius)
    lines = [
        f"# generated by scripts/build_memory_pack.py",
        f"# start={start}",
        f"# radius={radius}",
        "# nodes=" + ",".join(view),
    ]
    for source in external:
        lines.append(f"# external-source={source}")
    lines.extend(files)
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--start", default="GO-G4")
    parser.add_argument("--radius", type=int, default=3)
    parser.add_argument("--check", type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    text = render(args.start, args.radius)

    if args.check:
        expected = args.check.read_text(encoding="utf-8")
        assert text == expected, f"generated memory pack drifted from {args.check}"
        print(f"PSI-MEMORY M5 SNAPSHOT PASS: {args.check}")

    if args.output:
        args.output.write_text(text, encoding="utf-8")
    elif not args.check:
        print(text, end="")


if __name__ == "__main__":
    main()
